(function () {
  const toast=document.getElementById('toast'); let toastTimer;
  const safe=(value)=>String(value??'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const set=(id,value)=>{ const el=document.getElementById(id); if(el) el.textContent=value; };
  window.OranlabUI={
    showToast(message){ if(!toast) return; clearTimeout(toastTimer); toast.textContent=message; toast.classList.add('show'); toastTimer=setTimeout(()=>toast.classList.remove('show'),2600); },
    setLoading(active){ const button=document.querySelector('.primary-button'); if(!button) return; button.disabled=active; button.classList.toggle('loading',active); const label=button.querySelector('span'); if(label) label.textContent=active?'Hesaplanıyor...':'Analiz Et'; },
    resetStats(){ ['statMs1','statMsx','statMs2','statIy05','statMs15','statMs25','statKg','statHomeGoal','statAwayGoal'].forEach(id=>set(id,'--%')); ['statAvgGoals','statAvgHalfGoals'].forEach(id=>set(id,'--')); set('resultCount','0 eşleşme'); set('confidenceValue','--'); set('sampleInfo','Analiz sonrası örneklem bilgisi gösterilir.'); const confidenceBar=document.getElementById('confidenceBar'); if(confidenceBar) confidenceBar.style.width='0%'; const scorePodium=document.getElementById('scorePodium'); if(scorePodium) scorePodium.innerHTML='<div><span>1</span><strong>--</strong><small>--%</small></div><div><span>2</span><strong>--</strong><small>--%</small></div><div><span>3</span><strong>--</strong><small>--%</small></div>'; },
    updateStats(data){ const s=data.stats; set('statMs1',`${s.ms1}%`); set('statMsx',`${s.msx}%`); set('statMs2',`${s.ms2}%`); set('statIy05',`${s.iy05}%`); set('statMs15',`${s.ms15}%`); set('statMs25',`${s.ms25}%`); set('statKg',`${s.kg}%`); set('statHomeGoal',`${s.homeGoal}%`); set('statAwayGoal',`${s.awayGoal}%`); set('statAvgGoals',s.avgGoals); set('statAvgHalfGoals',s.avgHalfGoals); set('resultCount',`${data.total.toLocaleString('tr-TR')} eşleşme · ${data.shown} gösteriliyor`); set('confidenceValue',data.confidence); set('sampleInfo',`${data.sampleSize.toLocaleString('tr-TR')} maçlık örneklem üzerinden hesaplandı.`); const confidenceBar=document.getElementById('confidenceBar'); if(confidenceBar) confidenceBar.style.width=`${data.confidence}%`; const top=[...(data.topScores||[])]; while(top.length<3) top.push({score:'--',percentage:0}); const scorePodium=document.getElementById('scorePodium'); if(scorePodium) scorePodium.innerHTML=top.slice(0,3).map((x,i)=>`<div><span>${i+1}</span><strong>${safe(x.score)}</strong><small>%${safe(x.percentage)}</small></div>`).join(''); },

    renderRows(rows){ const body=document.getElementById('tableBody'); if(!body) return; if(!rows.length)return this.showEmptyState('Eşleşen maç bulunamadı','Farklı değer veya tolerans deneyebilirsin.'); body.innerHTML=rows.map(row=>`<tr><td><strong>${safe(row.league||'-')}</strong><small class="cell-meta">${safe(row.year||'')} ${safe(row.match_time||'')}</small></td><td>${safe(row.home||'-')}</td><td>${safe(row.away||'-')}</td><td><span class="score-badge">${safe(row.half_score||'-')}</span></td><td><span class="score-badge final-score">${safe(row.full_score||'-')}</span></td><td><span class="similarity-badge">%${safe(row.similarity)}</span><small class="cell-meta">${safe(row.ms1)} · ${safe(row.msx)} · ${safe(row.ms2)} | ${safe(row.barrier||'-')}</small></td></tr>`).join(''); },
    showEmptyState(message='Henüz analiz yapılmadı',detail='Yukarıdaki alanları doldurup “Analiz Et” butonuna bas.'){ const body=document.getElementById('tableBody'); if(!body) return; body.innerHTML=`<tr class="empty-row"><td colspan="6"><div class="empty-state"><span>⌁</span><strong>${safe(message)}</strong><small>${safe(detail)}</small></div></td></tr>`; }
  };
})();
