window.OranlabUI=(()=>{
  const $=id=>document.getElementById(id);
  const statMap={ms1:'statMs1',msx:'statMsx',ms2:'statMs2',iy05:'statIy05',ms15:'statMs15',ms25:'statMs25',kg:'statKg',homeGoal:'statHomeGoal',awayGoal:'statAwayGoal'};
  let currentRows=[];
  const pct=v=>`${Number(v||0)}%`;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function showToast(m){const t=$('toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2800)}
  function setLoading(v){document.body.classList.toggle('loading',v)}
  function showEmptyState(title='Henüz analiz yapılmadı',sub='Oranları girip Analiz Et butonuna bas.'){const b=$('tableBody');if(b)b.innerHTML=`<tr class="empty-row"><td colspan="8"><div class="empty-state"><span>⌁</span><strong>${esc(title)}</strong><small>${esc(sub)}</small></div></td></tr>`}
  function setText(id,val){if($(id))$(id).textContent=val}
  function resetStats(){Object.values(statMap).forEach(id=>setText(id,'--%'));['statAvgGoals','statAvgHalfGoals'].forEach(id=>setText(id,'--'));['oddsTotal','filteredTotal'].forEach(id=>setText(id,'0 maç'));['countMs1','countMsx','countMs2','countKg','countMs25','countIy05'].forEach(id=>setText(id,'0 / 0 maç'));setText('resultCount','0 eşleşme');setText('confidenceValue','--');setText('confidenceLabel','ANALİZ BEKLENİYOR');setText('confidenceStars','☆ ☆ ☆ ☆ ☆');if($('confidenceBar'))$('confidenceBar').style.width='0%';if($('confidenceRing'))$('confidenceRing').style.strokeDashoffset='314';if($('resultDonut'))$('resultDonut').style.background='conic-gradient(var(--green) 0 33.33%,var(--blue) 33.33% 66.66%,var(--purple) 66.66% 100%)';document.querySelectorAll('.metric>i b,.score-bars em').forEach(x=>x.style.width='0%');currentRows=[]}
  function updateStats(data){const s=data.stats||{},total=Number(data.total||0);for(const [k,id] of Object.entries(statMap))setText(id,pct(s[k]));setText('statAvgGoals',s.avgGoals??'--');setText('statAvgHalfGoals',s.avgHalfGoals??'--');setText('resultCount',`${total.toLocaleString('tr-TR')} eşleşme`);setText('oddsTotal',`${Number(data.oddsTotal||0).toLocaleString('tr-TR')} maç`);setText('filteredTotal',`${total.toLocaleString('tr-TR')} maç`);setText('chartTotal',total.toLocaleString('tr-TR'));const counts={Ms1:Math.round(total*(s.ms1||0)/100),Msx:Math.round(total*(s.msx||0)/100),Ms2:Math.round(total*(s.ms2||0)/100),Kg:Math.round(total*(s.kg||0)/100),Ms25:Math.round(total*(s.ms25||0)/100),Iy05:Math.round(total*(s.iy05||0)/100)};for(const [k,v] of Object.entries(counts))setText(`count${k}`,`${v.toLocaleString('tr-TR')} / ${total.toLocaleString('tr-TR')} maç`);setText('legendMs1',`${counts.Ms1.toLocaleString('tr-TR')} maç`);setText('legendMsx',`${counts.Msx.toLocaleString('tr-TR')} maç`);setText('legendMs2',`${counts.Ms2.toLocaleString('tr-TR')} maç`);setText('donutMain',pct(s.ms1));document.querySelectorAll('.metric').forEach(card=>{const n=parseFloat(card.querySelector(':scope>strong')?.textContent)||0;const bar=card.querySelector(':scope>i b');if(bar)bar.style.width=`${Math.min(100,n)}%`});const a=Number(s.ms1||0),b=Number(s.msx||0),c=Number(s.ms2||0);if($('resultDonut'))$('resultDonut').style.background=`conic-gradient(var(--green) 0 ${a}%,var(--blue) ${a}% ${a+b}%,var(--purple) ${a+b}% ${a+b+c}%,#142b35 ${a+b+c}% 100%)`;const conf=Number(data.confidence||0);setText('confidenceValue',conf);setText('confidenceLabel',conf>=75?'YÜKSEK GÜVEN':conf>=50?'ORTA GÜVEN':'DÜŞÜK ÖRNEKLEM');setText('confidenceStars',`${'★ '.repeat(Math.round(conf/20))}${'☆ '.repeat(5-Math.round(conf/20))}`.trim());if($('confidenceBar'))$('confidenceBar').style.width=`${conf}%`;if($('confidenceRing'))$('confidenceRing').style.strokeDashoffset=String(314-(314*conf/100));setText('sampleInfo',`${Number(data.sampleSize||0).toLocaleString('tr-TR')} maçlık örneklem üzerinden hesaplandı.`);setText('filterSummary',data.halfScore?`İlk yarı ${data.halfScore} filtresi aktif`:'İlk yarı filtresi uygulanmadı');const arr=data.topScores||[];const max=Math.max(...arr.map(x=>Number(x.count||0)),1);if($('scoreBars'))$('scoreBars').innerHTML=[0,1,2].map(i=>{const x=arr[i]||{};const w=Math.round((Number(x.count||0)/max)*100);return `<p><b>${esc(x.score||'--')}</b><i><em style="width:${w}%"></em></i><span>${Number(x.count||0).toLocaleString('tr-TR')} (%${Number(x.percentage||0)})</span></p>`}).join('')}
  function renderRows(rows=[]){currentRows=Array.isArray(rows)?rows:[];const b=$('tableBody');if(!b)return;if(!currentRows.length)return showEmptyState('Eşleşme bulunamadı','Filtreleri değiştirip yeniden dene.');b.innerHTML=currentRows.map(r=>`<tr><td>${esc(r.year||'-')}</td><td>${esc(r.league||'-')}</td><td>${esc(r.home||'-')}</td><td>${esc(r.away||'-')}</td><td><span class="score-badge">${esc(r.half_score||'-')}</span></td><td><span class="score-badge">${esc(r.full_score||'-')}</span></td><td>${[r.ms1,r.msx,r.ms2].map(v=>v??'-').join(' - ')}</td><td class="similarity">%${Number(r.similarity??0)}</td></tr>`).join('')}
  function exportCsv(){if(!currentRows.length)return showToast('İndirilecek eşleşme bulunmuyor.');const head=['Yıl','Lig','Ev Sahibi','Deplasman','İlk Yarı','Maç Sonucu','MS1','MSX','MS2','Barem','Benzerlik'];const lines=[head,...currentRows.map(r=>[r.year,r.league,r.home,r.away,r.half_score,r.full_score,r.ms1,r.msx,r.ms2,r.barrier,r.similarity])].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';'));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`oranlab-eslesen-maclar-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);showToast('Eşleşmeler Excel uyumlu CSV olarak indirildi.')}
  document.addEventListener('DOMContentLoaded',()=>{if($('excelButton'))$('excelButton').addEventListener('click',exportCsv)});
  return{showToast,setLoading,showEmptyState,resetStats,updateStats,renderRows,exportCsv}
})();
